/**
 * Classification Intent Constants for Workplace AI Assistant
 */
export const INTENTS = {
  DOCUMENT_QA: "DOCUMENT_QA",
  DOCUMENT_SUMMARY: "DOCUMENT_SUMMARY",
  POLICY_EXPLANATION: "POLICY_EXPLANATION",

  TASK_ASSISTANCE: "TASK_ASSISTANCE",
  PRODUCTIVITY_COACHING: "PRODUCTIVITY_COACHING",
  MEETING_ASSISTANCE: "MEETING_ASSISTANCE",
  EMAIL_DRAFTING: "EMAIL_DRAFTING",
  TRANSLATION: "TRANSLATION",

  WORKPLACE_WELLBEING: "WORKPLACE_WELLBEING",
  BREATHING_EXERCISE: "BREATHING_EXERCISE",
  DAILY_MOTIVATION: "DAILY_MOTIVATION",

  GENERAL_GOVERNMENT: "GENERAL_GOVERNMENT",
  CRISIS_SUPPORT: "CRISIS_SUPPORT",
  CONVERSATION_CLOSING: "CONVERSATION_CLOSING",
  UNKNOWN: "UNKNOWN",
};
